// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grntcukxgeyzvynebufw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybnRjdWt4Z2V5enZ5bmVidWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mzc1MDMsImV4cCI6MjA3MjMxMzUwM30.3wpOgjOjf6x6aBhbxOGeZjD_Sf6eVl8u9PFtGH2TcAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});